data:
  raw_path: data/raw/mlops_dataset_v3.csv
  processed_path: data/processed/
  target_column: visiteurs

model:
  type: RandomForestRegressor
  n_estimators: 100
  max_depth: 10
  random_state: 42

training:
  test_size: 0.2
  val_size: 0.1
  shuffle: true

mlflow:
  tracking_uri: ./mlruns
  experiment_name: "visiteurs_prediction"