# Configuration centralisée des hyperparamètres - Projet Visiteurs

dataset:
  name: "visiteurs"
  test_size: 0.2
  val_size: 0.1
  random_state: 42

preprocessing:
  scaler: "standard"  # Options: standard, minmax, robust
  handle_missing: "mean"  # Options: mean, median, drop
  outlier_threshold: 3  # Standard deviations

feature_engineering:
  polynomial_features: true
  degree: 2
  interaction_only: false
  feature_selection: true
  n_features_to_select: 10

model_visiteurs:
  type: "RandomForestRegressor"
  n_estimators: 200
  max_depth: 8
  min_samples_split: 4
  min_samples_leaf: 2
  random_state: 42

optuna:
  n_trials: 50
  timeout: 3600  # 1 hour
  n_jobs: 1
  sampler: "TPE"  # TPE, Random, Grid
  pruner: "MedianPruner"
  direction: "maximize"

mlflow:
  tracking_uri: "./mlruns"
  experiment_name: "visiteurs-prediction-experiment"
  run_name: "default-run"
  log_models: true
  log_artifacts: true

evaluation:
  cv_folds: 5
  scoring: "r2"  # For regression: r2, neg_mean_squared_error, neg_mean_absolute_error
  generate_plots: true
  save_predictions: true

monitoring:
  enabled: true
  drift_detection:
    threshold_std: 2.0
    method: "advanced"
  alerts:
    thresholds:
      warning:
        drift_percentage: 20
        critical_features: 1
      critical:
        drift_percentage: 40
        critical_features: 3
    notification:
      enabled: true
      methods: ["console", "file"]
  monitoring_features:
    - num_users
    - std_age
    - is_touristique
  history:
    enabled: true
    max_entries: 100
